# Site settings
title: eugielimpin
email: eugiellimpin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal internet space of Eugie Limpin.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://eugielimpin.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
